### ISSUE TITLE
As a user of any type, I want to come to home page, see a list of businesses close to me, and top rated businesses.

### ISSUE THREAD

**Issue by omriza5** [FACN7/wajjbat-frontend#1]
- [x] Fetch user’s location with their approval, and get closest businesses, send to backend & retrieve closest businesses #11.
- [x] Fetch top rated buinesses #10.
- [x] [Create business table in DB](https://github.com/FACN7/wajjbat-backend/issues/9) 
- [x] A home page displaying list of closest businesses, and top rated businesses, which matches design #12.
