### ISSUE TITLE
As a user of any type, I want to switch between Arabic & English 

### ISSUE THREAD

**Issue by HosenAgbaria** [FACN7/wajjbat-frontend#2]
- [x]  Button on navbar to switch the language #16
- [x]  Update the written content based on language #15
- [x]  Update the layout (RtL for Arabic, LtR for English)  #17

**Comment by Karyum** [comment]
we have done this next thing is add all the translations #34
